; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-cyd

[env:esp32-cyd]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = 
	pre:tools/check_bassgroove_fields.py
build_flags = 
	-std=gnu++14
	-DCORE_DEBUG_LEVEL=1
	-DCYD_USE_NEW_UI=0
lib_deps = 
	bblanchon/ArduinoJson @ ^6.21.5
	lovyan03/LovyanGFX @ ^1.1.12
