#pragma once

namespace ui::theme {

struct UiMetrics {
  static constexpr int ScreenW = 320;
  static constexpr int ScreenH = 240;
  static constexpr int OuterMargin = 8;
  static constexpr int TopBarH = 32;
  static constexpr int BottomNavH = 40;
  static constexpr int ContentTop = 32;
  static constexpr int ContentBottom = 196;
  static constexpr int ContentH = 164;
  static constexpr int TopBarTransportX = 16;
  static constexpr int TopBarTransportY = 12;
  static constexpr int TopBarTransportW = 160;
  static constexpr int TopBarTransportH = 20;
  static constexpr int TopBarMetricsX = 188;
  static constexpr int TopBarMetricsY = 12;
  static constexpr int TopBarMetricsW = 124;
  static constexpr int TopBarMetricsH = 20;
  static constexpr int TopBarTextBaselineY = 16;
  static constexpr int BottomNavButtonYInset = 4;
  static constexpr int BottomNavButtonW = 60;
  static constexpr int BottomNavButtonH = 32;
  static constexpr int MixHeaderX = 12;
  static constexpr int MixHeaderY = 46;
  static constexpr int MixHeaderW = 120;
  static constexpr int MixHeaderH = 48;
  static constexpr int MixMasterTextX = 140;
  static constexpr int MixMasterTextY = 52;
  static constexpr int MixMasterTextW = 132;
  static constexpr int MixMasterTextH = 16;
  static constexpr int MixMasterTextCursorX = 144;
  static constexpr int MixMasterTextCursorY = 56;
  static constexpr int MixFaderY = 102;
  static constexpr int MixFaderW = 40;
  static constexpr int MixFaderH = 90;
  static constexpr int MixFaderGap = 20;
  static constexpr int MixFaderStartX = 20;
  static constexpr int MixFaderDirtyPadding = 2;
  static constexpr int MixFaderDirtyLabelExtraH = 16;
  static constexpr int PerformRingsX = 12;
  static constexpr int PerformRingsY = 42;
  static constexpr int PerformRingsW = 176;
  static constexpr int PerformRingsH = 142;
  static constexpr int PerformControlsX = 204;
  static constexpr int PerformPlayY = 46;
  static constexpr int PerformControlW = 104;
  static constexpr int PerformButtonH = 34;
  static constexpr int PerformMuteY = 86;
  static constexpr int PerformCardY = 126;
  static constexpr int PerformCardH = 44;
  static constexpr int PerformTrackStripY = 126;
  static constexpr int PerformTrackStripX = 204;
  static constexpr int PerformTrackChipW = 50;
  static constexpr int PerformTrackChipH = 18;
  static constexpr int PerformTrackChipGap = 4;
  static constexpr int PerformTrackStripPadX = 0;
  static constexpr int PerformBpmX = 204;
  static constexpr int PerformBpmY = 174;
  static constexpr int PerformBpmW = 104;
  static constexpr int PerformBpmH = 16;
  static constexpr int PatternToolsButtonX = 12;
  static constexpr int PatternToolsButtonY = 172;
  static constexpr int PatternToolsButtonW = 120;
  static constexpr int PatternToolsButtonH = 20;
  static constexpr int PatternToolsModalX = 52;
  static constexpr int PatternToolsModalY = 74;
  static constexpr int PatternToolsModalW = 216;
  static constexpr int PatternToolsModalH = 118;
  static constexpr int PatternToolsActionW = 92;
  static constexpr int PatternToolsActionH = 26;
  static constexpr int PatternToolsActionX1 = 64;
  static constexpr int PatternToolsActionX2 = 164;
  static constexpr int PatternToolsActionY1 = 108;
  static constexpr int PatternToolsActionY2 = 140;
  static constexpr int ProjectToastX = 80;
  static constexpr int ProjectToastY = 176;
  static constexpr int ProjectToastW = 160;
  static constexpr int ProjectToastH = 18;
  static constexpr int RadiusSm = 4;
  static constexpr int RadiusMd = 8;
  static constexpr int TouchMinW = 40;
  static constexpr int TouchMinH = 32;
};

} // namespace ui::theme
