name: PlatformIO Build

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar PlatformIO
        run: pip install --upgrade platformio

      - name: Compilar Firmware
        run: pio run -e esp32-cyd

      - name: Upload dos artefatos do build
        uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32-cyd
          path: .pio/build/esp32-cyd/
          if-no-files-found: warn
