name: PlatformIO Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Compilar Firmware
        uses: karniv00l/platformio-run-action@v1
        with:
          # Apontando para o ambiente exato do seu platformio.ini
          environments: "esp32-cyd"
          project-dir: "."
